/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppYieldAiRouteImport } from './routes/_app.yield-ai'
import { Route as AppUploadRouteImport } from './routes/_app.upload'
import { Route as AppStorageAiRouteImport } from './routes/_app.storage-ai'
import { Route as AppSeedAiRouteImport } from './routes/_app.seed-ai'
import { Route as AppQuantumRouteImport } from './routes/_app.quantum'
import { Route as AppDatabaseRouteImport } from './routes/_app.database'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCropAiRouteImport } from './routes/_app.crop-ai'
import { Route as AppAdminRouteImport } from './routes/_app.admin'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppYieldAiRoute = AppYieldAiRouteImport.update({
  id: '/yield-ai',
  path: '/yield-ai',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppStorageAiRoute = AppStorageAiRouteImport.update({
  id: '/storage-ai',
  path: '/storage-ai',
  getParentRoute: () => AppRoute,
} as any)
const AppSeedAiRoute = AppSeedAiRouteImport.update({
  id: '/seed-ai',
  path: '/seed-ai',
  getParentRoute: () => AppRoute,
} as any)
const AppQuantumRoute = AppQuantumRouteImport.update({
  id: '/quantum',
  path: '/quantum',
  getParentRoute: () => AppRoute,
} as any)
const AppDatabaseRoute = AppDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCropAiRoute = AppCropAiRouteImport.update({
  id: '/crop-ai',
  path: '/crop-ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/crop-ai': typeof AppCropAiRoute
  '/dashboard': typeof AppDashboardRoute
  '/database': typeof AppDatabaseRoute
  '/quantum': typeof AppQuantumRoute
  '/seed-ai': typeof AppSeedAiRoute
  '/storage-ai': typeof AppStorageAiRoute
  '/upload': typeof AppUploadRoute
  '/yield-ai': typeof AppYieldAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/crop-ai': typeof AppCropAiRoute
  '/dashboard': typeof AppDashboardRoute
  '/database': typeof AppDatabaseRoute
  '/quantum': typeof AppQuantumRoute
  '/seed-ai': typeof AppSeedAiRoute
  '/storage-ai': typeof AppStorageAiRoute
  '/upload': typeof AppUploadRoute
  '/yield-ai': typeof AppYieldAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/crop-ai': typeof AppCropAiRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/database': typeof AppDatabaseRoute
  '/_app/quantum': typeof AppQuantumRoute
  '/_app/seed-ai': typeof AppSeedAiRoute
  '/_app/storage-ai': typeof AppStorageAiRoute
  '/_app/upload': typeof AppUploadRoute
  '/_app/yield-ai': typeof AppYieldAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin'
    | '/crop-ai'
    | '/dashboard'
    | '/database'
    | '/quantum'
    | '/seed-ai'
    | '/storage-ai'
    | '/upload'
    | '/yield-ai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin'
    | '/crop-ai'
    | '/dashboard'
    | '/database'
    | '/quantum'
    | '/seed-ai'
    | '/storage-ai'
    | '/upload'
    | '/yield-ai'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_app/admin'
    | '/_app/crop-ai'
    | '/_app/dashboard'
    | '/_app/database'
    | '/_app/quantum'
    | '/_app/seed-ai'
    | '/_app/storage-ai'
    | '/_app/upload'
    | '/_app/yield-ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/yield-ai': {
      id: '/_app/yield-ai'
      path: '/yield-ai'
      fullPath: '/yield-ai'
      preLoaderRoute: typeof AppYieldAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/storage-ai': {
      id: '/_app/storage-ai'
      path: '/storage-ai'
      fullPath: '/storage-ai'
      preLoaderRoute: typeof AppStorageAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seed-ai': {
      id: '/_app/seed-ai'
      path: '/seed-ai'
      fullPath: '/seed-ai'
      preLoaderRoute: typeof AppSeedAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quantum': {
      id: '/_app/quantum'
      path: '/quantum'
      fullPath: '/quantum'
      preLoaderRoute: typeof AppQuantumRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/database': {
      id: '/_app/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof AppDatabaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crop-ai': {
      id: '/_app/crop-ai'
      path: '/crop-ai'
      fullPath: '/crop-ai'
      preLoaderRoute: typeof AppCropAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCropAiRoute: typeof AppCropAiRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDatabaseRoute: typeof AppDatabaseRoute
  AppQuantumRoute: typeof AppQuantumRoute
  AppSeedAiRoute: typeof AppSeedAiRoute
  AppStorageAiRoute: typeof AppStorageAiRoute
  AppUploadRoute: typeof AppUploadRoute
  AppYieldAiRoute: typeof AppYieldAiRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCropAiRoute: AppCropAiRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDatabaseRoute: AppDatabaseRoute,
  AppQuantumRoute: AppQuantumRoute,
  AppSeedAiRoute: AppSeedAiRoute,
  AppStorageAiRoute: AppStorageAiRoute,
  AppUploadRoute: AppUploadRoute,
  AppYieldAiRoute: AppYieldAiRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
